config/routes.rb
Rails.application.routes.draw do
  root 'auth#new'
  resources :likes, only: [:create, :destroy]
  resources :followings, only: [:create, :destroy]
  resources :opinions, only: [:index, :create, :destroy]
  resources :users, only: [:index, :new, :show, :create]
  resources :auth, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User', foreign_key: 'FollowerId'
  belongs_to :followed, class_name: 'User', foreign_key: 'FollowedId'

  validate :cannot_follow_self

  private

  def cannot_follow_self
    errors.add(:followed, 'You cannot follow yourself.') if follower == followed
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :opinion
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  validates :Text, presence: true, length: { maximum: 200,
                                             too_long: 'Your opinion should be a maximum of 200 characters.' }

  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId'
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  validates :Username, presence: true, length: { maximum: 12 }, uniqueness: true
  validates :FullName, presence: true, length: { maximum: 30 }

  has_many :opinions, foreign_key: 'AuthorId', dependent: :destroy
  has_many :follower_relationships, foreign_key: 'FollowedId', class_name: 'Following', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :following_relationships, foreign_key: 'FollowerId', class_name: 'Following', dependent: :destroy
  has_many :following, through: :following_relationships, source: :followed

  has_many :likes
  has_many :liked_opinions, through: :likes, source: :opinion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def require_login
    return if helpers.user_signed_in?

    respond_to do |format|
      format.html { redirect_to new_auth_path, notice: 'You must be logged in to access this section' }
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = authenticate(auth_params)

    respond_to do |format|
      if @user
        session[:username] = @user.Username
        session[:user_id] = @user.id
        format.html { redirect_to opinions_path, notice: 'successfully logged in' }
      else
        format.html { redirect_to new_auth_path, notice: 'User not found!' }
      end
    end
  end

  def destroy
    session[:username] = nil
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to new_auth_path, notice: 'Successfuly logged out' }
    end
  end

  private

  def authenticate(username)
    User.find_by(username)
  end

  def auth_params
    params.require(:auth).permit(:Username)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:destroy]

  def create
    @following = helpers.current_user.following_relationships.build(FollowedId: params[:id])

    if @following.save
      redirect_to request.referrer, alert: 'Following was successfully created.'
    else
      redirect_to request.referrer, alert: 'Following was NOT created.'
    end
  end

  def destroy
    if @following.destroy
      redirect_to request.referrer, alert: 'Following was successfully destroyed.'
    else
      redirect_to request.referrer, alert: 'Following was NOT destroyed.'
    end
  end

  private

  def set_following
    @following = helpers.current_user.following_relationships.find_by(FollowedId: params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:destroy]

  def create
    @like = helpers.current_user.likes.build(opinion_id: params[:id])

    if @like.save
      redirect_to request.referrer, alert: 'You have liked this post.'

    else
      redirect_to request.referrer, alert: 'Like was Not created'
    end
  end

  def destroy
    if @like.destroy
      redirect_to request.referrer, alert: 'You have disliked this post'
    else
      redirect_to request.referrer, alert: 'Like was NOT destroyed.'
    end
  end

  private

  def set_like
    @like = helpers.current_user.likes.find_by(opinion_id: params[:id])
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]

  def index
    @opinion = Opinion.new
    @opinions = Opinion.all.includes(:author).order('created_at DESC')
    @users = User.all - helpers.current_user.following - [helpers.current_user]
  end

  def create
    @opinion = Opinion.new(AuthorId: session[:user_id], Text: opinion_params[:Text])

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to opinions_path, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  def opinion_params
    params.require(:opinion).permit(:Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  skip_before_action :require_login, only: %i[new create]

  def index
    @users = User.all
  end

  def show
    @opinion = Opinion.new
    @opinions = @user.opinions.order('created_at DESC')
    @users = @user.followers
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:username] = @user.Username
        session[:user_id] = @user.id
        format.html { redirect_to opinions_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:Username, :FullName, :Photo, :CoverImage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def home_nav_link(page)
    if page.eql?('home')
      link_to('Home', opinions_path, class: 'menu-item menu-item-selected')
    else
      link_to('Home', opinions_path, class: 'menu-item')
    end
  end

  def profile_nav_link(page)
    if page.eql?('profile')
      link_to('Profile', user_path(session[:user_id]), class: 'menu-item menu-item-selected')
    else
      link_to('Profile', user_path(session[:user_id]), class: 'menu-item')
    end
  end

  def people_nav_link(page)
    if page.eql?('people')
      link_to('People', users_path, class: 'menu-item menu-item-selected')
    else
      link_to('People', users_path, class: 'menu-item')
    end
  end

  def current_user
    User.find(session[:user_id])
  end

  def user_signed_in?
    true if session[:user_id]
  end

  def current_user_is_author?(opinion)
    opinion.AuthorId == session[:user_id]
  end

  def avatar_url(email)
    if email.nil? or email.empty?
      'default_avatar.jpg'
    else
      gravatar_id = Digest::MD5.hexdigest(email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png"
    end
  end

  def cover_image_url(link)
    if link.nil? or link.empty?
      'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ_9hWwp_Cwja6q3mq_WPDmJoSI4NEnHDaqKg&usqp=CAU'
    else
      link
    end
  end

  def following?(user)
    current_user.following.include?(user)
  end

  def current_user?(user)
    user.id == session[:user_id]
  end

  def liking?(opinion)
    current_user.liked_opinions.include?(opinion)
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<div class="header flex"> 
  <div class='flex logo-div'>
    <%= image_tag('Logo1.png', :class =>'avatar')%>
    <p class='author color-auto'>MAC</p>
  </div>
  <% unless user_signed_in? %>
    <h2 class='welcome'>Welcome ...</h2>
  <%end%>
  <div>
    <p class='author color-auto tagline'>Mad About Cycles</p>
  </div>
  <% if user_signed_in? %>
    <%= link_to 'Sign out', auth_path(session[:user_id]), method: :delete, class: 'nav-link-margin' %>
  <%end%>
</div>

app/views/application/_nav.html.erb
<nav class="nav">
  <div class='mini-profile nav-link-margin'>
    <div class='mini-profile-top flex'>
     <span><%= image_tag(avatar_url(current_user.Photo), :class =>'user_avatar')%></span>
     <span><%=current_user.FullName%></span>
    </div>
    <div class='mini-profile-top flex'>
      <div class='mini-profile-following'>
        <h2><%=current_user.following.count%></h2>
        <p>Following</p>
      </div>
      <div class='mini-profile-following'>
        <h2><%=current_user.followers.count%></h2>
        <p>Followers</p>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= home_nav_link(page) %>
    <%= profile_nav_link(page) %>
    <%= people_nav_link(page) %>
  <% end %>
</nav>

app/views/application/_opinion_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Text, "SAY SOMETHING", class: 'form-label' %>
    <%= form.text_area :Text, class: 'text-area', placeholder: 'Compose a new post' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: 'submit-btn' %>
  </div>
<% end %>

app/views/application/_users.html.erb
<table>
  <thead>
    <tr>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag(avatar_url(user.Photo), :class =>'avatar rounded')%></td>
        <td class='author color-auto'><%= user.FullName %></td>
        <td><%= link_to 'See Profile', user %></td>
        <td>
          <%if current_user?(user)%>
            <button class='follow-btn me-btn'>Me</button>
          <%else%>
            <%if following?(user)%>
              <%= button_to 'Unfollow', following_path(id: user.id), method: 'delete', class: 'follow-btn unfollow-btn' %>
            <%else%>
              <%= button_to 'Follow', followings_path(id: user.id), method: 'post', class: 'follow-btn' %>
            <%end%>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/followings/_form.html.erb
<%= form_with(model: following, local: true) do |form| %>
  <% if following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
        <% following.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :FollowerId %>
    <%= form.number_field :FollowerId %>
  </div>

  <div class="field">
    <%= form.label :FollowedId %>
    <%= form.number_field :FollowedId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followings</h1>

<table>
  <thead>
    <tr>
      <th>Followerid</th>
      <th>Followedid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.FollowerId %></td>
        <td><%= following.FollowedId %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Followerid:</strong>
  <%= @following.FollowerId %>
</p>

<p>
  <strong>Followedid:</strong>
  <%= @following.FollowedId %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MACycles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with(model: like, local: true) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.user_id %></td>
        <td><%= like.post_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @like.post_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/opinions/_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Text, "SAY SOMETHING", class: 'form-label' %>
    <%= form.text_area :Text, class: 'text-area', placeholder: 'Compose a new post' %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: 'submit-btn' %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'opinion_form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<main class='main flex'>
  <%= render 'nav', page: 'home' %>
  <div class='right-pane'>
    <%= render 'header'%>
    <div class='flex'>
      <div class='home-opinions'>
      <p id="notice"><%= notice %></p>
        <div class='posts-header'>
          <h2>POSTS</h2>
        </div>
        <div class='posts-area'>
          <div class='new-post white-area'>
            <%= render 'opinion_form', opinion: @opinion %>
          </div>
          <div class='new-post white-area'>
            <div class='latest-posts-header'>
              <h2 class='lower-margin'>Latest posts</h2>
            </div>
            <table>
              <thead>
                <tr>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                </tr>
              </thead>

              <tbody>
                <% @opinions.each do |opinion| %>
                  <tr>
                    <td><%= image_tag(avatar_url(opinion.author.Photo), :class =>'avatar')%></td>
                    <td>
                      <div>
                        <p class='author color-auto'><%= opinion.author.FullName %></p>
                        <p><%= opinion.Text %></p>
                      </div>
                    </td>
                    
                    <td>
                      <%if current_user_is_author?(opinion)%>
                        <%= link_to 'Delete', opinion, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>
                    </td>
                    <td>
                      <% likes_count = opinion.likes.count%>
                      <p><%= likes_count%> Like<%= likes_count == 1? '' : 's'%></p>
                      <%if liking?(opinion)%>
                        <%= button_to 'Dislike', like_path(id: opinion.id), method: 'delete', class: 'follow-btn unfollow-btn' %>
                      <%else%>
                        <%= button_to 'Like', likes_path(id: opinion.id), method: 'post', class: 'follow-btn' %>
                      <%end%>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
          </div>
        </div>
      </div>
      <div class='who-to-follow'>
        <div class='posts-header'>
          <h2 class='lower-margin'>WHO TO FOLLOW</h2>
        </div>
        <%= render 'users' %>
      </div>
    </div>
  </div>
</main>

app/views/opinions/new.html.erb
<main class='main flex'>
  <%= render 'nav', page: 'people' %>
  <div class='right-pane'>
    <%= render 'header'%>
    <div class='flex'>
      <div class='home-opinions'>
      <p id="notice"><%= notice %></p>
        <div class='posts-header'>
          <h2>NEW OPINION</h2>
        </div>
        <div class='posts-area'>
          <%= render 'opinion_form', opinion: @opinion %>
          <%= link_to 'Discard', opinions_path %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authorid:</strong>
  <%= @opinion.AuthorId %>
</p>

<p>
  <strong>Text:</strong>
  <%= @opinion.Text %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Username %>
    <%= form.text_field :Username %>
  </div>

  <div class="field">
    <%= form.label :FullName %>
    <%= form.text_field :FullName %>
  </div>

  <div class="field">
    <%= form.label :Photo, 'Enter your gravatar email (Optional)' %>
    <%= form.text_field :Photo %>
  </div>

  <div class="field">
    <%= form.label :CoverImage, 'Enter a cover-image link (Optional)' %>
    <%= form.text_field :CoverImage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<main class='main flex'>
  <%= render 'nav', page: 'people' %>
  <div class='right-pane'>
    <%= render 'header'%>
    <div class='flex'>
      <div class='home-opinions'>
      <p id="notice"><%= notice %></p>
        <div class='posts-header'>
          <h2>USERS</h2>
        </div>
        <div class='posts-area'>
          <%= render 'users' %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<%= render 'header'%>
<p id="notice"><%= notice %></p>
<div class='flex signin-div'>
  <h1 class='lower-margin'>Sign up</h1>
  <%= render 'form', user: @user %>
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<main class='main flex'>
  <% current_user?(@user) ? page = 'profile' : page = 'none' %>
  <%= render 'nav', page: page %>
  <div class='right-pane'>
    <%= render 'header'%>
    <div class='flex'>
      <div class='home-opinions'>
      <p id="notice"><%= notice %></p>
        <div class="cover-image-div">
          <%= image_tag(cover_image_url(@user.CoverImage), :class =>'cover-image')%>
        </div>
        <div class='posts-header'>
          <h2>POSTS</h2>
        </div>
        <div class='posts-area'>
          <div class='new-post white-area'>
            <%= render 'opinion_form', opinion: @opinion %>
          </div>
          <div class='new-post white-area'>
            <div class='latest-posts-header'>
              <h2 class='lower-margin'>Latest posts</h2>
            </div>
            <table>
              <thead>
                <tr>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                  <th colspan="1"></th>
                </tr>
              </thead>

              <tbody>
                <% @opinions.each do |opinion| %>
                  <tr>
                    <td><%= image_tag(avatar_url(opinion.author.Photo), :class =>'avatar')%></td>
                    <td>
                      <div>
                        <p class='author color-auto'><%= opinion.author.FullName %></p>
                        <p><%= opinion.Text %></p>
                      </div>
                    </td>
                    
                    <td>
                      <%if current_user_is_author?(opinion)%>
                        <%= link_to 'Delete', opinion, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%end%>
                    </td>
                    <td>
                      <% likes_count = opinion.likes.count%>
                      <p><%= likes_count%> Like<%= likes_count == 1? '' : 's'%></p>
                      <%if liking?(opinion)%>
                        <%= button_to 'Dislike', like_path(id: opinion.id), method: 'delete', class: 'follow-btn unfollow-btn' %>
                      <%else%>
                        <%= button_to 'Like', likes_path(id: opinion.id), method: 'post', class: 'follow-btn' %>
                      <%end%>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <br>
          </div>
        </div>
      </div>

      <div class='who-to-follow profile-aside'>
        <div class="profile-summary">
          <div class='profile-picture'>
            <%= image_tag(avatar_url(@user.Photo), :class =>'profile-avatar rounded')%>
            <p class='author color-auto'><%=@user.FullName%></p>
            <%if current_user?(@user)%>
              <button class='follow-btn me-btn'>Me</button>
            <%else%>
              <%if following?(@user)%>
                <%= button_to 'Unfollow', following_path(id: @user.id), method: 'delete', class: 'follow-btn unfollow-btn' %>
              <%else%>
                <%= button_to 'Follow', followings_path(id: @user.id), method: 'post', class: 'follow-btn' %>
              <%end%>
            <%end%>
          </div>
          <div class='flex mini-profile-top flex lower-margin'>
            <div class='mini-profile-following user-stats'>
              <% opinions_count = @opinions.count%>
              <h2><%=opinions_count%></h2>
              <p>Post<%= opinions_count == 1? '' : 's'%></p>
            </div>
            <div class='mini-profile-following user-stats'>
              <h2><%=@user.following.count%></h2>
              <p>Following</p>
            </div>
            <div class='mini-profile-following user-stats'>
              <h2><%=@user.followers.count%></h2>
              <p>Followers</p>
            </div>
          </div>
        </div>
        <div class='followers'>
          <div class='posts-header'>
            <h2 class='lower-margin'>FOLLOWED BY</h2>
          </div>
          <%= render 'users' %>
        </div>
      </div>
    </div>
  </div>
</main>